
development:
  adapter: postgresql
  encoding: unicode
  database: bobstar_development
  pool: 5
  username: bobstar
  password: bobstsucks

test:
  adapter: postgresql
  encoding: unicode
  database: bobstar_test
  pool: 5
  username: bobstar
  password: bobstsucks

production:
  adapter: postgresql
  encoding: unicode
  database: bobstar_production
  pool: 5
  username: bobstar
  password: bobstsucks